save_dir: logfile/vgg
model_name: VGG
model_args:
  type: VGG11
  num_class: 10
  total_layer: 16
data:
  name: CIFAR10
  train:
    name: CIFAR10
    dataset_path: ../../data
  val:
    name: CIFAR10
    dataset_path: ../../data
  batch_size: 64
  input_size: [3, 32, 32]
schedule:
#  resume:
#  load_model: YOUR_MODEL_PATH
  optimizer:
    name: SGD
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.00004
  warmup:
    name: linear
    steps: 0 # 300
    ratio: 0.1
  total_epochs: 200
  lr_schedule:
    name: MultiStepLR
    milestones: [ 60, 120, 160 ]
    gamma: 0.2
  val_intervals: 100 #100
log:
  interval: 10
weight_aggregation_interval: 5